### PR TITLE
Screenshots major cities

### PR DESCRIPTION
**Pull request by geo-tp**
From UNSORTED and some more

### CODE REVIEW

**Comment by GrenderG** [comment]
Hello @geo-tp! Did you check if we already have these screenshots but unsorted? This way they can be moved instead of added to avoid having yet more duplicated screenshots.

**Comment by geo-tp** [comment]
Many are the same as the ones you can find in UNSORTED folder yes

**Comment by GrenderG** [comment]
> Many are the same as the ones you can find in UNSORTED folder yes

Then please remove them from the UNSORTED folder. :)

**Comment by geo-tp** [comment]
it's done

**Pull request merged**
